inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - db/schema.rb
    - bin/*

Documentation:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environments/*'
    - 'config/environment.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config.ru'

RSpec/NestedGroups:
  Max: 4

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 50
  ExcludedMethods:
    - describe
    - context
    - path
    - get
    - patch
    - put
    - post
    - delete

Metrics/AbcSize:
  Max: 30
