inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - db/schema.rb
    - bin/*

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 50
  ExcludedMethods:
    - describe
    - context
    - path
    - get
    - patch
    - put
    - post
    - delete

Style/NumericPredicate:
  Exclude:
    - spec/**/*

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Metrics/AbcSize:
  Max: 30
