default: &default
  secret_key_base: <%= ENV['RAILS_SECRET_KEY_BASE'] %>

  redis_host: &redis_host
    host: <%= ENV.fetch('REDIS_HOST') { 'redis' } %>
    port: <%= ENV.fetch('REDIS_PORT') { 6379 } %>
    password: <%= ENV['REDIS_PASSWORD'] %>

  sidekiq_redis:
    <<: *redis_host
    db: <%= ENV.fetch('REDIS_SIDEKIQ_DB') { 0 } %>

  cache_redis:
    <<: *redis_host
    db: <%= ENV.fetch('REDIS_CACHE_DB') { 1 } %>

  telegram:
    token: <%= ENV['TELEGRAM_TOKEN'] %>
    webhook: <%= ENV['WEBHOOK_URL'] %>
    owners: <%= ENV['BOT_OWNERS']&.split(',')&.map(&:to_i) || [0] %>

  stop_covid_url: <%= ENV.fetch('STOPCOVID_URL') { 'https://xn--80aesfpebagmfblc0a.xn--p1ai' } %>
  context_size: <%= ENV.fetch('CONTEXT_SIZE') { 50 } %>
  allow_all: <%= ENV['ALLOW_TO_ALL'].to_s.downcase == 'true' %>
  sentry_dsn: <%= ENV['SENTRY_DSN'] %>
  release: <%= File.open('.version', 'r').read rescue 'Unknown' %>
  end_sentence:
    - '.'
    - '!'
    - '?'
    - '…'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
