FROM golang:1.18-alpine AS builder
WORKDIR /opt

ENV GO111MODULE "on"
ENV GOOS "linux"
ENV GOARCH "amd64"
ENV CGO_ENABLED 0

RUN apk --no-cache --update add ca-certificates curl git

COPY . /opt

RUN go mod download && \
    go mod verify && \
    go build -o /opt/receiver

FROM scratch
EXPOSE 3000

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /opt/receiver /

CMD ["/receiver"]
